using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace Pumpkin.Database;
public class Country
{
	//I would use a hashtable, but i dont have time for that rn and the dictionary uses one internally for lookup opperations... soooo.... idc
	static readonly Dictionary<short, string> CountyTable = new Dictionary<short, string>
	{
		{ 4, "Afghanistan" },
		{ 8, "Albania" },
		{ 12, "Algeria" },
		{ 16, "American Samoa" },
		{ 20, "Andorra" },
		{ 24, "Angola" },
		{ 660, "Anguilla" },
		{ 10, "Antarctica" },
		{ 28, "Antigua and Barbuda" },
		{ 32, "Argentina" },
		{ 51, "Armenia" },
		{ 533, "Aruba" },
		{ 36, "Australia" },
		{ 40, "Austria" },
		{ 31, "Azerbaijan" },
		{ 44, "Bahamas (the)" },
		{ 48, "Bahrain" },
		{ 50, "Bangladesh" },
		{ 52, "Barbados" },
		{ 112, "Belarus" },
		{ 56, "Belgium" },
		{ 84, "Belize" },
		{ 204, "Benin" },
		{ 60, "Bermuda" },
		{ 64, "Bhutan" },
		{ 68, "Bolivia (Plurinational State of)" },
		{ 535, "Bonaire, Sint Eustatius and Saba" },
		{ 70, "Bosnia and Herzegovina" },
		{ 72, "Botswana" },
		{ 74, "Bouvet Island" },
		{ 76, "Brazil" },
		{ 86, "British Indian Ocean Territory (the)" },
		{ 96, "Brunei Darussalam" },
		{ 100, "Bulgaria" },
		{ 854, "Burkina Faso" },
		{ 108, "Burundi" },
		{ 132, "Cabo Verde" },
		{ 116, "Cambodia" },
		{ 120, "Cameroon" },
		{ 124, "Canada" },
		{ 136, "Cayman Islands (the)" },
		{ 140, "Central African Republic (the)" },
		{ 148, "Chad" },
		{ 152, "Chile" },
		{ 156, "China" },
		{ 162, "Christmas Island" },
		{ 166, "Cocos (Keeling) Islands (the)" },
		{ 170, "Colombia" },
		{ 174, "Comoros (the)" },
		{ 180, "Congo (the Democratic Republic of the)" },
		{ 178, "Congo (the)" },
		{ 184, "Cook Islands (the)" },
		{ 188, "Costa Rica" },
		{ 191, "Croatia" },
		{ 192, "Cuba" },
		{ 531, "Curaçao" },
		{ 196, "Cyprus" },
		{ 203, "Czechia" },
		{ 384, "Côte d'Ivoire" },
		{ 208, "Denmark" },
		{ 262, "Djibouti" },
		{ 212, "Dominica" },
		{ 214, "Dominican Republic (the)" },
		{ 218, "Ecuador" },
		{ 818, "Egypt" },
		{ 222, "El Salvador" },
		{ 226, "Equatorial Guinea" },
		{ 232, "Eritrea" },
		{ 233, "Estonia" },
		{ 748, "Eswatini" },
		{ 231, "Ethiopia" },
		{ 238, "Falkland Islands (the) [Malvinas]" },
		{ 234, "Faroe Islands (the)" },
		{ 242, "Fiji" },
		{ 246, "Finland" },
		{ 250, "France" },
		{ 254, "French Guiana" },
		{ 258, "French Polynesia" },
		{ 260, "French Southern Territories (the)" },
		{ 266, "Gabon" },
		{ 270, "Gambia (the)" },
		{ 268, "Georgia" },
		{ 276, "Germany" },
		{ 288, "Ghana" },
		{ 292, "Gibraltar" },
		{ 300, "Greece" },
		{ 304, "Greenland" },
		{ 308, "Grenada" },
		{ 312, "Guadeloupe" },
		{ 316, "Guam" },
		{ 320, "Guatemala" },
		{ 831, "Guernsey" },
		{ 324, "Guinea" },
		{ 624, "Guinea-Bissau" },
		{ 328, "Guyana" },
		{ 332, "Haiti" },
		{ 334, "Heard Island and McDonald Islands" },
		{ 336, "Holy See (the)" },
		{ 340, "Honduras" },
		{ 344, "Hong Kong" },
		{ 348, "Hungary" },
		{ 352, "Iceland" },
		{ 356, "India" },
		{ 360, "Indonesia" },
		{ 364, "Iran (Islamic Republic of)" },
		{ 368, "Iraq" },
		{ 372, "Ireland" },
		{ 833, "Isle of Man" },
		{ 376, "Israel" },
		{ 380, "Italy" },
		{ 388, "Jamaica" },
		{ 392, "Japan" },
		{ 832, "Jersey" },
		{ 400, "Jordan" },
		{ 398, "Kazakhstan" },
		{ 404, "Kenya" },
		{ 296, "Kiribati" },
		{ 408, "Korea (the Democratic People's Republic of)" },
		{ 410, "Korea (the Republic of)" },
		{ 414, "Kuwait" },
		{ 417, "Kyrgyzstan" },
		{ 418, "Lao People's Democratic Republic (the)" },
		{ 428, "Latvia" },
		{ 422, "Lebanon" },
		{ 426, "Lesotho" },
		{ 430, "Liberia" },
		{ 434, "Libya" },
		{ 438, "Liechtenstein" },
		{ 440, "Lithuania" },
		{ 442, "Luxembourg" },
		{ 446, "Macao" },
		{ 450, "Madagascar" },
		{ 454, "Malawi" },
		{ 458, "Malaysia" },
		{ 462, "Maldives" },
		{ 466, "Mali" },
		{ 470, "Malta" },
		{ 584, "Marshall Islands (the)" },
		{ 474, "Martinique" },
		{ 478, "Mauritania" },
		{ 480, "Mauritius" },
		{ 175, "Mayotte" },
		{ 484, "Mexico" },
		{ 583, "Micronesia (Federated States of)" },
		{ 498, "Moldova (the Republic of)" },
		{ 492, "Monaco" },
		{ 496, "Mongolia" },
		{ 499, "Montenegro" },
		{ 500, "Montserrat" },
		{ 504, "Morocco" },
		{ 508, "Mozambique" },
		{ 104, "Myanmar" },
		{ 516, "Namibia" },
		{ 520, "Nauru" },
		{ 524, "Nepal" },
		{ 528, "Netherlands (the)" },
		{ 540, "New Caledonia" },
		{ 554, "New Zealand" },
		{ 558, "Nicaragua" },
		{ 562, "Niger (the)" },
		{ 566, "Nigeria" },
		{ 570, "Niue" },
		{ 574, "Norfolk Island" },
		{ 580, "Northern Mariana Islands (the)" },
		{ 578, "Norway" },
		{ 512, "Oman" },
		{ 586, "Pakistan" },
		{ 585, "Palau" },
		{ 275, "Palestine, State of" },
		{ 591, "Panama" },
		{ 598, "Papua New Guinea" },
		{ 600, "Paraguay" },
		{ 604, "Peru" },
		{ 608, "Philippines (the)" },
		{ 612, "Pitcairn" },
		{ 616, "Poland" },
		{ 620, "Portugal" },
		{ 630, "Puerto Rico" },
		{ 634, "Qatar" },
		{ 807, "Republic of North Macedonia" },
		{ 642, "Romania" },
		{ 643, "Russian Federation (the)" },
		{ 646, "Rwanda" },
		{ 638, "Réunion" },
		{ 652, "Saint Barthélemy" },
		{ 654, "Saint Helena, Ascension and Tristan da Cunha" },
		{ 659, "Saint Kitts and Nevis" },
		{ 662, "Saint Lucia" },
		{ 663, "Saint Martin (French part)" },
		{ 666, "Saint Pierre and Miquelon" },
		{ 670, "Saint Vincent and the Grenadines" },
		{ 882, "Samoa" },
		{ 674, "San Marino" },
		{ 678, "Sao Tome and Principe" },
		{ 682, "Saudi Arabia" },
		{ 686, "Senegal" },
		{ 688, "Serbia" },
		{ 690, "Seychelles" },
		{ 694, "Sierra Leone" },
		{ 702, "Singapore" },
		{ 534, "Sint Maarten (Dutch part)" },
		{ 703, "Slovakia" },
		{ 705, "Slovenia" },
		{ 90, "Solomon Islands" },
		{ 706, "Somalia" },
		{ 710, "South Africa" },
		{ 239, "South Georgia and the South Sandwich Islands" },
		{ 728, "South Sudan" },
		{ 724, "Spain" },
		{ 144, "Sri Lanka" },
		{ 729, "Sudan (the)" },
		{ 740, "Suriname" },
		{ 744, "Svalbard and Jan Mayen" },
		{ 752, "Sweden" },
		{ 756, "Switzerland" },
		{ 760, "Syrian Arab Republic" },
		{ 158, "Taiwan (Province of China)" },
		{ 762, "Tajikistan" },
		{ 834, "Tanzania, United Republic of" },
		{ 764, "Thailand" },
		{ 626, "Timor-Leste" },
		{ 768, "Togo" },
		{ 772, "Tokelau" },
		{ 776, "Tonga" },
		{ 780, "Trinidad and Tobago" },
		{ 788, "Tunisia" },
		{ 792, "Turkey" },
		{ 795, "Turkmenistan" },
		{ 796, "Turks and Caicos Islands (the)" },
		{ 798, "Tuvalu" },
		{ 800, "Uganda" },
		{ 804, "Ukraine" },
		{ 784, "United Arab Emirates (the)" },
		{ 826, "United Kingdom of Great Britain and Northern Ireland (the)" },
		{ 581, "United States Minor Outlying Islands (the)" },
		{ 840, "United States of America (the)" },
		{ 858, "Uruguay" },
		{ 860, "Uzbekistan" },
		{ 548, "Vanuatu" },
		{ 862, "Venezuela (Bolivarian Republic of)" },
		{ 704, "Viet Nam" },
		{ 92, "Virgin Islands (British)" },
		{ 850, "Virgin Islands (U.S.)" },
		{ 876, "Wallis and Futuna" },
		{ 732, "Western Sahara" },
		{ 887, "Yemen" },
		{ 894, "Zambia" },
		{ 716, "Zimbabwe" },
		{ 248, "Åland Islands" }
	};

	static readonly Dictionary<string, string> LanguageTable = new Dictionary<string, string>
	{
		{ "aar", "Afar" },
		{ "abk", "Abkhazian" },
		{ "ace", "Achinese" },
		{ "ach", "Acoli" },
		{ "ada", "Adangme" },
		{ "ady", "Adyghe; Adygei" },
		{ "afa", "Afro-Asiatic languages" },
		{ "afh", "Afrihili" },
		{ "afr", "Afrikaans" },
		{ "ain", "Ainu" },
		{ "aka", "Akan" },
		{ "akk", "Akkadian" },
		{ "ale", "Aleut" },
		{ "alg", "Algonquian languages" },
		{ "alt", "Southern Altai" },
		{ "amh", "Amharic" },
		{ "ang", "English, Old (ca.450–1100)" },
		{ "anp", "Angika" },
		{ "apa", "Apache languages" },
		{ "ara", "Arabic" },
		{ "arc", "Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)" },
		{ "arg", "Aragonese" },
		{ "arn", "Mapudungun; Mapuche" },
		{ "arp", "Arapaho" },
		{ "art", "Artificial languages" },
		{ "arw", "Arawak" },
		{ "asm", "Assamese" },
		{ "ast", "Asturian; Bable; Leonese; Asturleonese" },
		{ "ath", "Athapascan languages" },
		{ "aus", "Australian languages" },
		{ "ava", "Avaric" },
		{ "ave", "Avestan" },
		{ "awa", "Awadhi" },
		{ "aym", "Aymara" },
		{ "aze", "Azerbaijani" },
		{ "bad", "Banda languages" },
		{ "bai", "Bamileke languages" },
		{ "bak", "Bashkir" },
		{ "bal", "Baluchi" },
		{ "bam", "Bambara" },
		{ "ban", "Balinese" },
		{ "bas", "Basa" },
		{ "bat", "Baltic languages" },
		{ "bej", "Beja; Bedawiyet" },
		{ "bel", "Belarusian" },
		{ "bem", "Bemba" },
		{ "ben", "Bengali" },
		{ "ber", "Berber languages" },
		{ "bho", "Bhojpuri" },
		{ "bih", "Bihari languages" },
		{ "bik", "Bikol" },
		{ "bin", "Bini; Edo" },
		{ "bis", "Bislama" },
		{ "bla", "Siksika" },
		{ "bnt", "Bantu languages" },
		{ "tib", "Tibetan" },
		{ "bod", "Tibetan" },
		{ "bos", "Bosnian" },
		{ "bra", "Braj" },
		{ "bre", "Breton" },
		{ "btk", "Batak languages" },
		{ "bua", "Buriat" },
		{ "bug", "Buginese" },
		{ "bul", "Bulgarian" },
		{ "byn", "Blin; Bilin" },
		{ "cad", "Caddo" },
		{ "cai", "Central American Indian languages" },
		{ "car", "Galibi Carib" },
		{ "cat", "Catalan; Valencian" },
		{ "cau", "Caucasian languages" },
		{ "ceb", "Cebuano" },
		{ "cel", "Celtic languages" },
		{ "ces", "Czech" },
		{ "cze", "Czech" },
		{ "cha", "Chamorro" },
		{ "chb", "Chibcha" },
		{ "che", "Chechen" },
		{ "chg", "Chagatai" },
		{ "chk", "Chuukese" },
		{ "chm", "Mari" },
		{ "chn", "Chinook jargon" },
		{ "cho", "Choctaw" },
		{ "chp", "Chipewyan; Dene Suline" },
		{ "chr", "Cherokee" },
		{ "chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" },
		{ "chv", "Chuvash" },
		{ "chy", "Cheyenne" },
		{ "cmc", "Chamic languages" },
		{ "cnr", "Montenegrin" },
		{ "cop", "Coptic" },
		{ "cor", "Cornish" },
		{ "cos", "Corsican" },
		{ "cpe", "Creoles and pidgins, English based" },
		{ "cpf", "Creoles and pidgins, French-based" },
		{ "cpp", "Creoles and pidgins, Portuguese-based" },
		{ "cre", "Cree" },
		{ "crh", "Crimean Tatar; Crimean Turkish" },
		{ "crp", "Creoles and pidgins" },
		{ "csb", "Kashubian" },
		{ "cus", "Cushitic languages" },
		{ "wel", "Welsh" },
		{ "cym", "Welsh" },
		{ "dak", "Dakota" },
		{ "dan", "Danish" },
		{ "dar", "Dargwa" },
		{ "day", "Land Dayak languages" },
		{ "del", "Delaware" },
		{ "den", "Slave (Athapascan)" },
		{ "ger", "German" },
		{ "deu", "German" },
		{ "dgr", "Dogrib" },
		{ "din", "Dinka" },
		{ "div", "Divehi; Dhivehi; Maldivian" },
		{ "doi", "Dogri" },
		{ "dra", "Dravidian languages" },
		{ "dsb", "Lower Sorbian" },
		{ "dua", "Duala" },
		{ "dum", "Dutch, Middle (ca. 1050–1350)" },
		{ "dyu", "Dyula" },
		{ "dzo", "Dzongkha" },
		{ "efi", "Efik" },
		{ "egy", "Egyptian (Ancient)" },
		{ "eka", "Ekajuk" },
		{ "gre", "Greek, Modern (1453–)" },
		{ "ell", "Greek, Modern (1453–)" },
		{ "elx", "Elamite" },
		{ "eng", "English" },
		{ "enm", "English, Middle (1100–1500)" },
		{ "epo", "Esperanto" },
		{ "est", "Estonian" },
		{ "baq", "Basque" },
		{ "eus", "Basque" },
		{ "ewe", "Ewe" },
		{ "ewo", "Ewondo" },
		{ "fan", "Fang" },
		{ "fao", "Faroese" },
		{ "per", "Persian" },
		{ "fas", "Persian" },
		{ "fat", "Fanti" },
		{ "fij", "Fijian" },
		{ "fil", "Filipino; Pilipino" },
		{ "fin", "Finnish" },
		{ "fiu", "Finno-Ugrian languages" },
		{ "fon", "Fon" },
		{ "fra", "French" },
		{ "fre", "French" },
		{ "frm", "French, Middle (ca. 1400–1600)" },
		{ "fro", "French, Old (842–ca. 1400)" },
		{ "frr", "Northern Frisian" },
		{ "frs", "East Frisian Low Saxon" },
		{ "fry", "Western Frisian" },
		{ "ful", "Fulah" },
		{ "fur", "Friulian" },
		{ "gaa", "Ga" },
		{ "gay", "Gayo" },
		{ "gba", "Gbaya" },
		{ "gem", "Germanic languages" },
		{ "gez", "Geez" },
		{ "gil", "Gilbertese" },
		{ "gla", "Gaelic; Scottish Gaelic" },
		{ "gle", "Irish" },
		{ "glg", "Galician" },
		{ "glv", "Manx" },
		{ "gmh", "German, Middle High (ca. 1050–1500)" },
		{ "goh", "German, Old High (ca. 750–1050)" },
		{ "gon", "Gondi" },
		{ "gor", "Gorontalo" },
		{ "got", "Gothic" },
		{ "grb", "Grebo" },
		{ "grc", "Greek, Ancient (to 1453)" },
		{ "grn", "Guarani" },
		{ "gsw", "Swiss German; Alemannic; Alsatian" },
		{ "guj", "Gujarati" },
		{ "gwi", "Gwich'in" },
		{ "hai", "Haida" },
		{ "hat", "Haitian; Haitian Creole" },
		{ "hau", "Hausa" },
		{ "haw", "Hawaiian" },
		{ "heb", "Hebrew" },
		{ "her", "Herero" },
		{ "hil", "Hiligaynon" },
		{ "him", "Himachali languages; Pahari languages" },
		{ "hin", "Hindi" },
		{ "hit", "Hittite" },
		{ "hmn", "Hmong; Mong" },
		{ "hmo", "Hiri Motu" },
		{ "hrv", "Croatian" },
		{ "hsb", "Upper Sorbian" },
		{ "hun", "Hungarian" },
		{ "hup", "Hupa" },
		{ "hye", "Armenian" },
		{ "arm", "Armenian" },
		{ "iba", "Iban" },
		{ "ibo", "Igbo" },
		{ "ido", "Ido" },
		{ "iii", "Sichuan Yi; Nuosu" },
		{ "ijo", "Ijo languages" },
		{ "iku", "Inuktitut" },
		{ "ile", "Interlingue; Occidental" },
		{ "ilo", "Iloko" },
		{ "ina", "Interlingua (International Auxiliary Language Association)" },
		{ "inc", "Indo-Aryan languages" },
		{ "ind", "Indonesian" },
		{ "ine", "Indo-European languages" },
		{ "inh", "Ingush" },
		{ "ipk", "Inupiaq" },
		{ "ira", "Iranian languages" },
		{ "iro", "Iroquoian languages" },
		{ "isl", "Icelandic" },
		{ "ice", "Icelandic" },
		{ "ita", "Italian" },
		{ "jav", "Javanese" },
		{ "jbo", "Lojban" },
		{ "jpn", "Japanese" },
		{ "jpr", "Judeo-Persian" },
		{ "jrb", "Judeo-Arabic" },
		{ "kaa", "Kara-Kalpak" },
		{ "kab", "Kabyle" },
		{ "kac", "Kachin; Jingpho" },
		{ "kal", "Kalaallisut; Greenlandic" },
		{ "kam", "Kamba" },
		{ "kan", "Kannada" },
		{ "kar", "Karen languages" },
		{ "kas", "Kashmiri" },
		{ "geo", "Georgian" },
		{ "kat", "Georgian" },
		{ "kau", "Kanuri" },
		{ "kaw", "Kawi" },
		{ "kaz", "Kazakh" },
		{ "kbd", "Kabardian" },
		{ "kha", "Khasi" },
		{ "khi", "Khoisan languages" },
		{ "khm", "Central Khmer" },
		{ "kho", "Khotanese; Sakan" },
		{ "kik", "Kikuyu; Gikuyu" },
		{ "kin", "Kinyarwanda" },
		{ "kir", "Kirghiz; Kyrgyz" },
		{ "kmb", "Kimbundu" },
		{ "kok", "Konkani" },
		{ "kom", "Komi" },
		{ "kon", "Kongo" },
		{ "kor", "Korean" },
		{ "kos", "Kosraean" },
		{ "kpe", "Kpelle" },
		{ "krc", "Karachay-Balkar" },
		{ "krl", "Karelian" },
		{ "kro", "Kru languages" },
		{ "kru", "Kurukh" },
		{ "kua", "Kuanyama; Kwanyama" },
		{ "kum", "Kumyk" },
		{ "kur", "Kurdish" },
		{ "kut", "Kutenai" },
		{ "lad", "Ladino" },
		{ "lah", "Lahnda" },
		{ "lam", "Lamba" },
		{ "lao", "Lao" },
		{ "lat", "Latin" },
		{ "lav", "Latvian" },
		{ "lez", "Lezghian" },
		{ "lim", "Limburgan; Limburger; Limburgish" },
		{ "lin", "Lingala" },
		{ "lit", "Lithuanian" },
		{ "lol", "Mongo" },
		{ "loz", "Lozi" },
		{ "ltz", "Luxembourgish; Letzeburgesch" },
		{ "lua", "Luba-Lulua" },
		{ "lub", "Luba-Katanga" },
		{ "lug", "Ganda" },
		{ "lui", "Luiseno" },
		{ "lun", "Lunda" },
		{ "luo", "Luo (Kenya and Tanzania)" },
		{ "lus", "Lushai" },
		{ "mad", "Madurese" },
		{ "mag", "Magahi" },
		{ "mah", "Marshallese" },
		{ "mai", "Maithili" },
		{ "mak", "Makasar" },
		{ "mal", "Malayalam" },
		{ "man", "Mandingo" },
		{ "map", "Austronesian languages" },
		{ "mar", "Marathi" },
		{ "mas", "Masai" },
		{ "mdf", "Moksha" },
		{ "mdr", "Mandar" },
		{ "men", "Mende" },
		{ "mga", "Irish, Middle (900–1200)" },
		{ "mic", "Mi'kmaq; Micmac" },
		{ "min", "Minangkabau" },
		{ "mis", "Uncoded languages" },
		{ "mac", "Macedonian" },
		{ "mkd", "Macedonian" },
		{ "mkh", "Mon-Khmer languages" },
		{ "mlg", "Malagasy" },
		{ "mlt", "Maltese" },
		{ "mnc", "Manchu" },
		{ "mni", "Manipuri" },
		{ "mno", "Manobo languages" },
		{ "moh", "Mohawk" },
		{ "mon", "Mongolian" },
		{ "mos", "Mossi" },
		{ "mao", "Māori" },
		{ "mri", "Māori" },
		{ "may", "Malay" },
		{ "msa", "Malay" },
		{ "mul", "Multiple languages" },
		{ "mun", "Munda languages" },
		{ "mus", "Creek" },
		{ "mwl", "Mirandese" },
		{ "mwr", "Marwari" },
		{ "bur", "Burmese" },
		{ "mya", "Burmese" },
		{ "myn", "Mayan languages" },
		{ "myv", "Erzya" },
		{ "nah", "Nahuatl languages" },
		{ "nai", "North American Indian languages" },
		{ "nap", "Neapolitan" },
		{ "nau", "Nauru" },
		{ "nav", "Navajo; Navaho" },
		{ "nbl", "Ndebele, South; South Ndebele" },
		{ "nde", "Ndebele, North; North Ndebele" },
		{ "ndo", "Ndonga" },
		{ "nds", "Low German; Low Saxon; German, Low; Saxon, Low" },
		{ "nep", "Nepali" },
		{ "new", "Nepal Bhasa; Newari" },
		{ "nia", "Nias" },
		{ "nic", "Niger-Kordofanian languages" },
		{ "niu", "Niuean" },
		{ "nld", "Dutch; Flemish" },
		{ "dut", "Dutch; Flemish" },
		{ "nno", "Norwegian Nynorsk; Nynorsk, Norwegian" },
		{ "nob", "Bokmål, Norwegian; Norwegian Bokmål" },
		{ "nog", "Nogai" },
		{ "non", "Norse, Old" },
		{ "nor", "Norwegian" },
		{ "nqo", "N'Ko" },
		{ "nso", "Pedi; Sepedi; Northern Sotho" },
		{ "nub", "Nubian languages" },
		{ "nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa" },
		{ "nya", "Chichewa; Chewa; Nyanja" },
		{ "nym", "Nyamwezi" },
		{ "nyn", "Nyankole" },
		{ "nyo", "Nyoro" },
		{ "nzi", "Nzima" },
		{ "oci", "Occitan (post 1500)" },
		{ "oji", "Ojibwa" },
		{ "ori", "Oriya" },
		{ "orm", "Oromo" },
		{ "osa", "Osage" },
		{ "oss", "Ossetian; Ossetic" },
		{ "ota", "Turkish, Ottoman (1500–1928)" },
		{ "oto", "Otomian languages" },
		{ "paa", "Papuan languages" },
		{ "pag", "Pangasinan" },
		{ "pal", "Pahlavi" },
		{ "pam", "Pampanga; Kapampangan" },
		{ "pan", "Panjabi; Punjabi" },
		{ "pap", "Papiamento" },
		{ "pau", "Palauan" },
		{ "peo", "Persian, Old (ca. 600–400 B.C.)" },
		{ "phi", "Philippine languages" },
		{ "phn", "Phoenician" },
		{ "pli", "Pali" },
		{ "pol", "Polish" },
		{ "pon", "Pohnpeian" },
		{ "por", "Portuguese" },
		{ "pra", "Prakrit languages" },
		{ "pro", "Provençal, Old (to 1500); Old Occitan (to 1500)" },
		{ "pus", "Pushto; Pashto" },
		{ "qaa_qtz", "Reserved for local use" },
		{ "que", "Quechua" },
		{ "raj", "Rajasthani" },
		{ "rap", "Rapanui" },
		{ "rar", "Rarotongan; Cook Islands Māori" },
		{ "roa", "Romance languages" },
		{ "roh", "Romansh" },
		{ "rom", "Romany" },
		{ "ron", "Romanian; Moldavian; Moldovan" },
		{ "rum", "Romanian; Moldavian; Moldovan" },
		{ "run", "Rundi" },
		{ "rup", "Aromanian; Arumanian; Macedo-Romanian[b]" },
		{ "rus", "Russian" },
		{ "sad", "Sandawe" },
		{ "sag", "Sango" },
		{ "sah", "Yakut" },
		{ "sai", "South American Indian languages" },
		{ "sal", "Salishan languages" },
		{ "sam", "Samaritan Aramaic" },
		{ "san", "Sanskrit" },
		{ "sas", "Sasak" },
		{ "sat", "Santali" },
		{ "scn", "Sicilian" },
		{ "sco", "Scots" },
		{ "sel", "Selkup" },
		{ "sem", "Semitic languages" },
		{ "sga", "Irish, Old (to 900)" },
		{ "sgn", "Sign Languages" },
		{ "shn", "Shan" },
		{ "sid", "Sidamo" },
		{ "sin", "Sinhala; Sinhalese" },
		{ "sio", "Siouan languages" },
		{ "sit", "Sino-Tibetan languages" },
		{ "sla", "Slavic languages" },
		{ "slk", "Slovak" },
		{ "slo", "Slovak" },
		{ "slv", "Slovenian" },
		{ "sma", "Southern Sami" },
		{ "sme", "Northern Sami" },
		{ "smi", "Sami languages" },
		{ "smj", "Lule Sami" },
		{ "smn", "Inari Sami" },
		{ "smo", "Samoan" },
		{ "sms", "Skolt Sami" },
		{ "sna", "Shona" },
		{ "snd", "Sindhi" },
		{ "snk", "Soninke" },
		{ "sog", "Sogdian" },
		{ "som", "Somali" },
		{ "son", "Songhai languages" },
		{ "sot", "Sotho, Southern" },
		{ "spa", "Spanish; Castilian" },
		{ "sqi", "Albanian" },
		{ "alb", "Albanian" },
		{ "srd", "Sardinian" },
		{ "srn", "Sranan Tongo" },
		{ "srp", "Serbian" },
		{ "srr", "Serer" },
		{ "ssa", "Nilo-Saharan languages" },
		{ "ssw", "Swati" },
		{ "suk", "Sukuma" },
		{ "sun", "Sundanese" },
		{ "sus", "Susu" },
		{ "sux", "Sumerian" },
		{ "swa", "Swahili" },
		{ "swe", "Swedish" },
		{ "syc", "Classical Syriac" },
		{ "syr", "Syriac" },
		{ "tah", "Tahitian" },
		{ "tai", "Tai languages" },
		{ "tam", "Tamil" },
		{ "tat", "Tatar" },
		{ "tel", "Telugu" },
		{ "tem", "Timne" },
		{ "ter", "Tereno" },
		{ "tet", "Tetum" },
		{ "tgk", "Tajik" },
		{ "tgl", "Tagalog" },
		{ "tha", "Thai" },
		{ "tig", "Tigre" },
		{ "tir", "Tigrinya" },
		{ "tiv", "Tiv" },
		{ "tkl", "Tokelau" },
		{ "tlh", "Klingon; tlhIngan-Hol" },
		{ "tli", "Tlingit" },
		{ "tmh", "Tamashek" },
		{ "tog", "Tonga (Nyasa)" },
		{ "ton", "Tonga (Tonga Islands)" },
		{ "tpi", "Tok Pisin" },
		{ "tsi", "Tsimshian" },
		{ "tsn", "Tswana" },
		{ "tso", "Tsonga" },
		{ "tuk", "Turkmen" },
		{ "tum", "Tumbuka" },
		{ "tup", "Tupi languages" },
		{ "tur", "Turkish" },
		{ "tut", "Altaic languages" },
		{ "tvl", "Tuvalu" },
		{ "twi", "Twi" },
		{ "tyv", "Tuvinian" },
		{ "udm", "Udmurt" },
		{ "uga", "Ugaritic" },
		{ "uig", "Uighur; Uyghur" },
		{ "ukr", "Ukrainian" },
		{ "umb", "Umbundu" },
		{ "und", "Undetermined" },
		{ "urd", "Urdu" },
		{ "uzb", "Uzbek" },
		{ "vai", "Vai" },
		{ "ven", "Venda" },
		{ "vie", "Vietnamese" },
		{ "vol", "Volapük" },
		{ "vot", "Votic" },
		{ "wak", "Wakashan languages" },
		{ "wal", "Wolaitta; Wolaytta" },
		{ "war", "Waray" },
		{ "was", "Washo" },
		{ "wen", "Sorbian languages" },
		{ "wln", "Walloon" },
		{ "wol", "Wolof" },
		{ "xal", "Kalmyk; Oirat" },
		{ "xho", "Xhosa" },
		{ "yao", "Yao" },
		{ "yap", "Yapese" },
		{ "yid", "Yiddish" },
		{ "yor", "Yoruba" },
		{ "ypk", "Yupik languages" },
		{ "zap", "Zapotec" },
		{ "zbl", "Blissymbols; Blissymbolics; Bliss" },
		{ "zen", "Zenaga" },
		{ "zgh", "Standard Moroccan Tamazight" },
		{ "zha", "Zhuang; Chuang" },
		{ "zho", "Chinese" },
		{ "chi", "Chinese" },
		{ "znd", "Zande languages" },
		{ "zul", "Zulu" },
		{ "zun", "Zuni" },
		{ "zxx", "No linguistic content; Not applicable" },
		{ "zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" },
	};

}
